const examples = [
  { label: "Urban transport", topic: "Should cities restrict private cars in downtown areas?", a: "Cities should restrict private cars downtown. Less traffic creates safer streets, cleaner air, and stronger local commerce. Congestion pricing shows demand can be managed while transit investment improves access.", b: "Cities should not restrict private cars downtown. Small businesses rely on easy access for customers, and many workers cannot depend on public transit. Restrictions could unfairly burden families and outer suburbs." },
  { label: "Four-day week", topic: "Should companies adopt a four-day work week?", a: "A four-day week improves focus and retention. Pilot programs show productivity can hold steady when needless meetings are reduced.", b: "A four-day week creates operational pressure for customer-facing teams and may fail businesses needing continuous coverage." },
  { label: "AI in schools", topic: "Should students be allowed to use AI tools in school?", a: "AI tools should be permitted with guidance because they give students immediate feedback and teach a core modern literacy.", b: "AI tools should be restricted because they can obscure original thinking before students master foundational skills." }
];
// This fixture follows the exact judgment JSON contract. Replace it with the API response later.
const judgment = {
  motion: "Should cities restrict private cars in downtown areas?",
  pull_quote: "A policy case is strongest when it answers the costs it creates.",
  winner: "A",
  overall_score: { a: 7.4, b: 6.0 },
  argument_profile: { logic: { a: 7.3, b: 6.7 }, evidence: { a: 7.3, b: 5.7 }, rebuttal: { a: 7.7, b: 5.7 } },
  claims: {
    a: [
      { claim: "Car-light centers create safer, more usable public streets.", logic_score: 8, evidence_score: 7, rebuttal_score: 8, analysis: "The causal chain is clear and it answers the access concern through public-space benefits. It uses a plausible mechanism, though the evidence remains general rather than local." },
      { claim: "Congestion pricing has reduced traffic in comparable city centers.", logic_score: 7, evidence_score: 8, rebuttal_score: 7, analysis: "Comparable-city precedent supplies specific evidence and supports the policy mechanism. The argument would be stronger with attention to differences between those cities and the proposed setting." },
      { claim: "Exemptions and transit investment can limit the burden on workers.", logic_score: 7, evidence_score: 7, rebuttal_score: 8, analysis: "This directly addresses Side B's strongest equity objection. It supplies a coherent mitigation, although its evidence for adequacy is not fully developed." }
    ],
    b: [
      { claim: "Small businesses need nearby driving and parking access.", logic_score: 7, evidence_score: 5, rebuttal_score: 6, analysis: "The concern is logically relevant, but it is asserted without local business data. It only partially engages Side A's claim that a car-light center can improve local commerce." },
      { claim: "Restrictions burden people outside reliable transit networks.", logic_score: 7, evidence_score: 6, rebuttal_score: 6, analysis: "This is Side B's strongest fairness point and identifies a real implementation constraint. It loses rebuttal strength because it does not show why exemptions and transit investment cannot address the burden." },
      { claim: "Delivery and emergency access make a full restriction impractical.", logic_score: 6, evidence_score: 6, rebuttal_score: 5, analysis: "The claim identifies an operational limitation, but assumes a full restriction despite policies commonly using exemptions. It does not directly rebut Side A's qualified proposal." }
    ]
  },
  final_verdict: "Side A wins because its congestion-pricing precedent and worker-exemption proposal jointly establish both a policy benefit and a response to Side B's principal access objection. Side B's strongest claim is that poor transit can burden outer-suburb workers, but it does not explain why targeted exemptions and transit investment are inadequate. The small-business concern is relevant but unsupported by local evidence and does not overcome Side A's contrary mechanism. The delivery objection also misses the availability of exemptions, leaving it a limitation rather than a decisive refutation."
};
function normalizeJudgment(result) { const toClaims = (claims) => claims.map((claim) => [claim.claim, claim.logic_score, claim.evidence_score, claim.rebuttal_score, claim.analysis]); return { sideA: { name: "Side A", score: result.overall_score.a, claims: toClaims(result.claims.a) }, sideB: { name: "Side B", score: result.overall_score.b, claims: toClaims(result.claims.b) }, reasoning: result.final_verdict, pullQuote: result.pull_quote }; }
const verdict = normalizeJudgment(judgment);
const app = document.querySelector('#app');
function inputScreen() { app.innerHTML = `<section class="page"><header class="hero"><div class="mark">±</div><p class="eyebrow">Argument intelligence</p><h1>Let the best case win.</h1><p>Paste two sides of a debate. Get a clear, claim-by-claim judgment in seconds.</p></header><section class="card input-card"><label class="field-label">Debate topic <span class="optional">(optional)</span><input id="topic" class="topic" placeholder="e.g. Should cities restrict cars downtown?"></label><div class="sides"><label class="field-label">Side A<span class="hint">The proposition or first position</span><textarea id="side-a" placeholder="Paste this side's argument here..."></textarea></label><label class="field-label">Side B<span class="hint">The opposition or counter-position</span><textarea id="side-b" placeholder="Paste this side's argument here..."></textarea></label></div><p id="error" class="error">Please fill in both sides before submitting.</p><div class="action-row"><div><p class="try-label">TRY AN EXAMPLE</p><div class="chips">${examples.map((x,i)=>`<button class="chip" data-example="${i}">${x.label}</button>`).join('')}</div></div><button id="judge" class="primary" disabled>Judge this debate →</button></div></section><p class="footer-note">✦ Built for thoughtful disagreements, not hot takes.</p></section>`; const a=document.querySelector('#side-a'),b=document.querySelector('#side-b'),button=document.querySelector('#judge'); const valid=()=>{button.disabled=!(a.value.trim()&&b.value.trim())}; a.oninput=b.oninput=valid; document.querySelectorAll('[data-example]').forEach(el=>el.onclick=()=>{const x=examples[el.dataset.example];document.querySelector('#topic').value=x.topic;a.value=x.a;b.value=x.b;valid()}); button.onclick=loading; }
function loading(){ const topic=document.querySelector('#topic').value; let step=0, labels=['Extracting claims...','Scoring arguments...','Testing rebuttals...','Reaching a verdict...']; app.innerHTML=`<section class="page loading"><div><div class="spinner"></div><p id="status">${labels[0]}</p><small>Reading both sides with care</small></div></section>`; const clock=setInterval(()=>{step=(step+1)%labels.length;document.querySelector('#status').textContent=labels[step]},750); setTimeout(()=>{clearInterval(clock);dashboard(topic)},3100); }
function polygon(vals){const cx=150,cy=130,r=88;return vals.map((v,i)=>{const angle=(-90+i*120)*Math.PI/180,rad=r*v/10;return `${cx+Math.cos(angle)*rad},${cy+Math.sin(angle)*rad}`}).join(' ')}
function claims(side){return `<div><div class="column-title"><h3>${side.name}</h3><span class="pill">${side.score.toFixed(1)} overall</span></div>${side.claims.map((c,i)=>`<article class="card claim"><button class="claim-toggle"><span class="number">${i+1}</span><span class="claim-text">${c[0]}</span><span class="arrow">⌄</span></button><div class="details"><div class="metrics">${[['Logic',c[1]],['Evidence',c[2]],['Rebuttal',c[3]]].map(x=>`<div class="metric"><small>${x[0]}</small><strong class="count" data-target="${x[1]}">0.0</strong></div>`).join('')}</div><p class="note">✦ ${c[4]}</p></div></article>`).join('')}</div>`}
function dashboard(topic){topic=topic||judgment.motion;const winner=judgment.winner==='A'?'Side A':'Side B';app.innerHTML=`<section class="page"><header class="topbar"><div class="brand"><i>±</i> AI Debate Judge</div><button class="ghost" id="reset">← New debate</button></header><section class="card banner"><div class="banner-left"><div class="icon-box">⚖</div><div><span class="badge">JUDGMENT DELIVERED</span><h1>${winner} wins</h1><p class="sub">The higher weighted score determines the judgment.</p></div></div><div class="score"><small>OVERALL SCORE</small><strong>${verdict.sideA.score.toFixed(1)} <span>vs</span> ${verdict.sideB.score.toFixed(1)}</strong></div></section><section class="overview"><article class="card pad"><p class="eyebrow">Argument profile</p><h2 class="section-title">How the cases compare</h2><svg class="chart" viewBox="0 0 300 270"><g transform="translate(0,5)" fill="none" stroke="#dbe3dc"><polygon points="150,42 226,174 74,174"/><polygon points="150,64 207,163 93,163"/><polygon points="150,86 188,152 112,152"/></g><g transform="translate(0,5)" font-family="DM Sans" font-size="11" font-weight="700" fill="#69736b"><text x="132" y="18">Logic</text><text x="237" y="190">Evidence</text><text x="21" y="190">Rebuttal</text></g><polygon transform="translate(0,5)" points="${polygon([judgment.argument_profile.logic.a,judgment.argument_profile.evidence.a,judgment.argument_profile.rebuttal.a])}" fill="#3a5c4738" stroke="#3a5c47" stroke-width="2"/><polygon transform="translate(0,5)" points="${polygon([judgment.argument_profile.logic.b,judgment.argument_profile.evidence.b,judgment.argument_profile.rebuttal.b])}" fill="#9aa69d25" stroke="#9aa69d" stroke-width="2"/></svg><div class="legend"><span><i class="dot"></i>Side A</span><span><i class="dot gray"></i>Side B</span></div></article><article class="card pad"><p class="eyebrow">The motion</p><h2 class="section-title">${topic}</h2><p class="ruling-quote">“${verdict.pullQuote}”</p><p class="sub">Explore each claim below to see how the ruling was reached.</p></article></section><section class="claims-header"><p class="eyebrow">Claim analysis</p><h2 class="section-title">Evidence, logic & response</h2><div class="claims">${claims(verdict.sideA)}${claims(verdict.sideB)}</div></section><section class="final"><p class="eyebrow">Final verdict</p><p>${verdict.reasoning}</p></section><button class="primary again" id="again">Judge another debate →</button></section>`;document.querySelectorAll('.claim-toggle').forEach(b=>b.onclick=()=>{const card=b.closest('.claim');card.classList.toggle('open');if(card.classList.contains('open'))card.querySelectorAll('.count').forEach(countUp)});document.querySelector('#reset').onclick=document.querySelector('#again').onclick=inputScreen; }
function countUp(el){const target=+el.dataset.target,start=performance.now(),duration=650;function frame(now){const p=Math.min((now-start)/duration,1);el.textContent=(target*(1-Math.pow(1-p,3))).toFixed(1);if(p<1)requestAnimationFrame(frame)}requestAnimationFrame(frame)} inputScreen();
