import { motion } from "framer-motion";
import { ArrowRight, CheckCircle2, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "./ui/button";
import { Card } from "./ui/card";
import { Textarea } from "./ui/textarea";

const examples = [
  { label: "Urban transport", topic: "Should cities restrict private cars in downtown areas?", a: "Cities should restrict private cars downtown. Less traffic creates safer streets, cleaner air, and stronger local commerce. Congestion pricing in cities such as London shows demand can be managed while transit investment improves access.", b: "Cities should not restrict private cars downtown. Small businesses rely on easy access for customers, and many workers cannot depend on public transit. Restrictions could unfairly burden families and people from the outer suburbs." },
  { label: "Four-day week", topic: "Should companies adopt a four-day work week?", a: "A four-day week improves focus and retention. Pilot programs show productivity can hold steady when needless meetings and fragmented work are reduced.", b: "A four-day week creates operational pressure for customer-facing teams. It may shift work into longer days and fail to suit businesses that need continuous coverage." },
  { label: "AI in schools", topic: "Should students be allowed to use AI tools in school?", a: "AI tools should be permitted with guidance because they can give every student immediate feedback and teach a core modern literacy.", b: "AI tools should be restricted because they can obscure original thinking and make assessment less reliable before students master foundational skills." }
];
const statuses = ["Extracting claims...", "Scoring arguments...", "Testing rebuttals...", "Reaching a verdict..."];
export interface InputValues { topic: string; sideA: string; sideB: string; }
export function InputScreen({ onSubmit }: { onSubmit: (values: InputValues) => Promise<void> }) {
  const [values, setValues] = useState<InputValues>({ topic: "", sideA: "", sideB: "" }); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [status, setStatus] = useState(0);
  useEffect(() => { if (!loading) return; const id = window.setInterval(() => setStatus((s) => (s + 1) % statuses.length), 1150); return () => window.clearInterval(id); }, [loading]);
  const submit = async () => { if (!values.sideA.trim() || !values.sideB.trim()) { setError("Please fill in both sides before submitting."); return; } setError(""); setLoading(true); try { await onSubmit(values); } finally { setLoading(false); } };
  const setExample = (example: typeof examples[number]) => { setValues({ topic: example.topic, sideA: example.a, sideB: example.b }); setError(""); };
  return <main className="mx-auto w-full max-w-6xl px-4 py-10 sm:px-6 sm:py-16"><motion.header initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} className="mx-auto mb-10 max-w-2xl text-center"><div className="mx-auto mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-primary text-white shadow-lg shadow-primary/20"><ScaleMark /></div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Argument intelligence</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Let the best case win.</h1><p className="mt-4 text-base leading-7 text-muted-foreground">Paste two sides of a debate. Get a clear, claim-by-claim judgment in seconds.</p></motion.header><Card className="mx-auto max-w-5xl p-5 sm:p-7"><label className="text-sm font-semibold">Debate topic <span className="font-normal text-muted-foreground">(optional)</span><input value={values.topic} onChange={(e) => setValues({ ...values, topic: e.target.value })} placeholder="e.g. Should cities restrict cars downtown?" className="mt-2 h-12 w-full rounded-xl border border-input bg-white px-4 text-sm outline-none focus:ring-2 focus:ring-primary/20" /></label><div className="mt-6 grid gap-5 md:grid-cols-2"><SideField label="Side A" hint="The proposition or first position" value={values.sideA} onChange={(sideA) => setValues({ ...values, sideA })} /><SideField label="Side B" hint="The opposition or counter-position" value={values.sideB} onChange={(sideB) => setValues({ ...values, sideB })} /></div>{error && <p role="alert" className="mt-4 flex items-center gap-2 text-sm font-medium text-primary"><CheckCircle2 size={16} />{error}</p>}<div className="mt-6 flex flex-col-reverse gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="mb-2 text-xs font-semibold text-muted-foreground">TRY AN EXAMPLE</p><div className="flex flex-wrap gap-2">{examples.map((ex) => <button key={ex.label} onClick={() => setExample(ex)} className="rounded-full border border-border bg-white px-3 py-1.5 text-xs font-medium text-muted-foreground transition hover:border-primary/30 hover:text-primary">{ex.label}</button>)}</div></div><Button size="lg" onClick={submit} disabled={loading || !values.sideA.trim() || !values.sideB.trim()}>{loading ? <><span className="h-4 w-4 animate-spin rounded-full border-2 border-white/35 border-t-white" />{statuses[status]}</> : <>Judge this debate <ArrowRight size={17} /></>}</Button></div></Card><p className="mt-5 text-center text-xs text-muted-foreground"><Sparkles className="mr-1 inline text-primary" size={13} />Built for thoughtful disagreements, not hot takes.</p></main>;
}
function SideField({ label, hint, value, onChange }: { label: string; hint: string; value: string; onChange: (value: string) => void }) { return <label className="block text-sm font-semibold">{label}<span className="mt-0.5 block text-xs font-normal text-muted-foreground">{hint}</span><Textarea value={value} onChange={(e) => onChange(e.target.value)} placeholder="Paste this side's argument here..." className="mt-3" /></label>; }
function ScaleMark() { return <span className="font-serif text-2xl font-bold">±</span>; }
