import { motion } from "framer-motion";
import { ArrowLeft, BarChart3, Scale } from "lucide-react";
import { ClaimCard } from "./ClaimCard";
import { RadarChartComparison } from "./RadarChartComparison";
import { WinnerBanner } from "./WinnerBanner";
import { Button } from "./ui/button";
import { Card } from "./ui/card";
import type { DebateSide, Verdict } from "../types";

export function VerdictDashboard({ verdict, onReset }: { verdict: Verdict; onReset: () => void }) {
  return <main className="mx-auto w-full max-w-6xl px-4 py-8 sm:px-6 sm:py-12"><header className="mb-7 flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-bold"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-white"><Scale size={16} /></div> AI Debate Judge</div><Button variant="ghost" size="sm" onClick={onReset}><ArrowLeft size={15} /> New debate</Button></header><WinnerBanner verdict={verdict} /><section className="mt-7 grid gap-7 lg:grid-cols-[.88fr_1.12fr]"><Card className="p-5 sm:p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Argument profile</p><h2 className="mt-1 text-xl font-bold">How the cases compare</h2></div><BarChart3 className="text-muted-foreground" size={20} /></div><RadarChartComparison sideA={verdict.sideA} sideB={verdict.sideB} /><div className="flex justify-center gap-5 text-xs font-semibold"><span className="flex items-center gap-1.5"><i className="h-2.5 w-2.5 rounded-full bg-primary" />{verdict.sideA.name}</span><span className="flex items-center gap-1.5 text-muted-foreground"><i className="h-2.5 w-2.5 rounded-full bg-[#9aa69d]" />{verdict.sideB.name}</span></div></Card><motion.section initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="rounded-2xl border border-border bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">The motion</p><h2 className="mt-2 text-2xl font-bold leading-tight">{verdict.topic}</h2><div className="mt-6 border-l-2 border-primary/30 pl-5"><p className="font-serif text-xl leading-8 text-foreground">“A debate is won not by having no weaknesses, but by answering them best.”</p><p className="mt-4 text-sm leading-6 text-muted-foreground">Explore each claim below to see how the ruling was reached.</p></div></motion.section></section><section className="mt-8"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Claim analysis</p><h2 className="mt-1 text-2xl font-bold">Evidence, logic & response</h2></div><div className="grid gap-6 lg:grid-cols-2"><ClaimColumn side={verdict.sideA} /><ClaimColumn side={verdict.sideB} /></div></section><section className="mt-8 rounded-3xl bg-primary px-6 py-8 text-primary-foreground shadow-[0_16px_36px_rgba(58,92,71,.18)] sm:px-9"><p className="text-xs font-bold uppercase tracking-[.17em] text-white/65">Final verdict</p><p className="mt-4 max-w-4xl font-serif text-2xl leading-9 sm:text-3xl sm:leading-10">{verdict.reasoning}</p></section><div className="mt-8 flex justify-center"><Button size="lg" onClick={onReset}>Judge another debate <ArrowLeft className="rotate-180" size={17} /></Button></div></main>;
}
function ClaimColumn({ side }: { side: DebateSide }) { return <div><div className="mb-3 flex items-center justify-between"><h3 className="text-lg font-bold">{side.name}</h3><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary">{side.overall_score.toFixed(1)} overall</span></div><div className="space-y-3">{side.claims.map((claim, index) => <ClaimCard key={claim.text} claim={claim} index={index} />)}</div></div>; }
